### ISSUE TITLE
[Task] Todo

### ISSUE THREAD

**Issue by tlambert03** [pyapp-kit/cmap#4]
- [x] work on namespacing and colormap string name parsing
- [ ] #19
- [ ] consider plugin system... or interface for registration
- [x] refine catalog mechanism
- [ ] continue to improve attributions and references
